### ISSUE TITLE
Forums vanish after adding What's New module and moving to different layout

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#248]
I'm a little boggled.  After adding the What's New module to my forum page, the forums became blank.  I tried deleting the new module, but even though I see all the groups and forums in the control panel, the page shows nothing

Has anyone seen this before?  Is it fixable?  I've probably changed enough things in trying to fix it to really break it, but its worth a try.  It was 6.1.4 when it broke. I've since upgraded to 6.1.5 as part of my attempt to fix.

![image](https://cloud.githubusercontent.com/assets/11527822/6761323/ff820c94-cf0e-11e4-8597-1daa22bc7c57.png)

**Comment by TBGoat** [comment]
I found the issue:  Message:Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

[dbo].[activeforums_Forums_List] is erroring when called, it looks like data got duplicated somehow.  I'm looking for a way to fix the table now.

**Comment by supermansrf** [comment]
I have a fix for this somewhere.  Give me a minute and I will dig it up

**Comment by supermansrf** [comment]
I hate referencing the old codeplex site because people already don't get the picture. But I ran into this a while ago.  I had my developer fix it for me.  Additionally, I ran into it again, but the script he sent me didn't work.  I had to ask him to do it again.  The problem I ran into was really similar to this.  Forums disappeared but it was for a specific user.  I never have been able to figure out why it happened, just figured out how to fix it.  Hopefully there is some info in here that can help you figure it out.  

If you do will you please report back as to what you found?  Like I said so far this has only affected 1-2 random users and both times it was tapatalk related (or so I thought).  I would love to know if this is true or if tapatalk was just a coincidence.  

https://activeforums.codeplex.com/discussions/446816

**Comment by supermansrf** [comment]
Sorry, the reason the script didn't work was possibly because I don't know what I'm doing with sql.  Only enough to tread water.  You can probably easily figure this out.  

Mine had to do with security I believe.

**Comment by TBGoat** [comment]
@supermansrf , thank you so much!

The below code works (just needed a few tweaks):

--Query 1: Check if bad data is present, for any user and forum combination 
SELECT COUNT(*) , forumID, UserId
FROM dbo.activeforums_Forums_Tracking 
group by ForumId, UserId 
having COUNT(*) > 1 

--Get Id of records which have bad data 
SELECT TrackingId 
FROM dbo.activeforums_Forums_Tracking t
JOIN
(SELECT  forumID, UserId
FROM dbo.activeforums_Forums_Tracking 
group by ForumId, UserId 
having COUNT(*) > 1 ) f
ON f.ForumId = t.ForumId
AND f.UserId = t.UserId

--Punish culprit record 
delete from dbo.activeforums_Forums_Tracking WHERE TrackingId IN (SELECT TrackingId 
FROM dbo.activeforums_Forums_Tracking t
JOIN
(SELECT  forumID, UserId
FROM dbo.activeforums_Forums_Tracking 
group by ForumId, UserId 
having COUNT(*) > 1 ) f
ON f.ForumId = t.ForumId
AND f.UserId = t.UserId)

**Comment by TBGoat** [comment]
I'm leaving this open, because its really not clear to me how changing the layout should have caused all this to happen.

**Comment by artfuld** [comment]
Did you try to reinstall the module when you had the problem? Since you changed the txt-file that might have reverted it back to the original.

**Comment by TBGoat** [comment]
Hi @artfuld.  I reinstalled about halfway through the problem and upgraded to the latest beta, but the problem had already begun before that.  It literally happened while I was moving things around on the page.  When I went into layout mode it was fine.  When I hit save and reverted to normal view it was gone.

**Comment by artfuld** [comment]
Oh sorry, I didn't read correct. I thought the layout-bit had something to do with the forumview-layout that we changed earlier.

**Comment by TBGoat** [comment]
Rereading all the comments, I /had/ installed tapatalk about a half hour prior. It could be related.

**Comment by supermansrf** [comment]
After that comment I'm convinced that its tapatalk causing the problem and not the whats new module.  I had a similar experience both times that it happened to me.  

Good news is tapatalk integration is getting completely rebuilt so this shouldn't happen any more.  You also shouldn't see the problem happen again.  I hope to have the new tapatalk integration done in the next 3 weeks so if you are building a new site and can hold off you may want to.  

I have had random issues where tapatalk also crashed the app pool.  This is really random and I can't duplicate it.  But there are times where I have to shut tapatalk off completely in order to keep the site up. I wait a few days/weeks and turn it back on; sometimes its fine sometimes it starts again.  

Glad you got it fixed.  Good deal
