### ISSUE TITLE
After new install, control panel forums link does nothing

### ISSUE THREAD

**Issue by TBGoat** [ActiveForums/ActiveForums#250]
I just installed Active Forums on a new portal and when I go to control panel to set things up, the Forums link does nothing.   I see Loading, please wait and then it goes back to whatever tab I was on.

Any suggestions?  Should I try uploading an earlier version than 6.1.5?

**Comment by artfuld** [comment]
What version of DNN is this?

**Comment by TBGoat** [comment]
7.4

**Comment by artfuld** [comment]
I will try a new install and see if I can reproduce the problem.
What error message shows in the event viewer?

**Comment by TBGoat** [comment]
It gets stranger.  There's no error message in the event viewer at all from the attempt to load forums.  However, when I tried to open module settings, two error messages popped.  I tried module settings on other pages and there were no errors at all:

1) Message:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
StackTrace:
InnerMessage:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
InnerStackTrace:
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.Services.Exceptions.Exceptions.ProcessModuleLoadException(String FriendlyMessage, Control ctrl, Exception exc, Boolean DisplayErrorMessage)

2)Message:Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

**Comment by TBGoat** [comment]
Actually, no idea what caused the module settings to do that on the first page, I added it to a second page and couldn't reproduce.  However, the issue with forums loading in the control panel persists.

**Comment by artfuld** [comment]
Tried installing on a new installation both with and without qualifiers, can't reproduce the error.

Could you try to reinstall af?

**Comment by artfuld** [comment]
Did you install the tapatalk plugin this time also?

**Comment by TBGoat** [comment]
I didn't install tapatalk, at least not yet.  Trying a reinstall.

**Comment by TBGoat** [comment]
Reinstalling fixed it.  No idea what happened the first time. Thanks!

**Comment by artfuld** [comment]
Was this a clean install of DNN aswell?

**Comment by johnhenley** [comment]
I want to say that I ran into this error as well when updating from 5.2.4 to 6.1.5.
I think the problem was that a SQL function (referenced by code added in 5.2.4) wasn't added to the SQL installer scripts until after 5.2.4 was actually released. And the 5.2.4 SqlDataProvider script was/is being incorrectly installed/skipped.

Try running this SQL scripts manually:

https://github.com/ActiveForums/ActiveForums/blob/master/sql/05.02.02.SqlDataProvider
https://github.com/ActiveForums/ActiveForums/blob/master/sql/05.02.04.SqlDataProvider
https://github.com/ActiveForums/ActiveForums/blob/master/sql/06.00.02.SqlDataProvider
https://github.com/ActiveForums/ActiveForums/blob/master/sql/06.01.03.SqlDataProvider

**Comment by TBGoat** [comment]
It was a clean install of DNN, yes.
