### ISSUE TITLE
Merge 2 forums?

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#254]
@tbgoat this one is directed at you.  I saw where you came up with a script to move a forum to a different portal ID.  Amazing and thank you for sharing.  I will hopefully one day be moving a lot of that kind of information to the website where it's easier to access.  A knowledge base for lack of better words.  This will be when someone else comes along to help with organization.  

That being said, I have something that I would love to get some input on.  I have 2 totally separate websites.  They are on separate installs of DNN completely.  Both on portal 0 on their own respective instance of DNN.  Separate database etc.  

These 2 sites are both on the same version of AF and have their own content.  We are working on a project where we will be merging these 2 websites.  All users from one will be imported to the other.  I have everything solved with the exception of the forum.  This is where I run into problems.  

These are private forums.  No unauthorized access.  Current members may not always have access. So leaving the old forum archived somewhere for members to access isn't a possibility.  This will mean keeping the 2 user databases sync'd.  I can't do that.  So my next step was going to be to convince the smaller forum to just let me abandon it.  Keep the content somewhere in case we (meaning admins) need to reference it and start over again.  

I would love to be able to move their forum content.  I immediately see this as a major undertaking and not even sure if its possible.  Here are a few things I've thought of already.

1.  User ID's won't match.  I thought maybe importing the users beginning with a very high user ID and try to keep them consistent?  So user ID 1001 would be 50001001.  This way I wouldn't ever have to worry about new user ID stepping over the imported ones?  

2.  Forum ID's and topic ID's could potentially be the same so same there possibly with the numbering.  

3.  Security won't match as role ID's would be different.  

I'm looking for some honest input here.  I know that nothing is impossible.  The challenge is trying to determine what is feasible and what is budget friendly.  Obviously if I had a team of SQL genius and a million dollar budget would probably pull this off.  But I also never thought that I would be able to migrate from DNN forum to AF and I did.  

Thoughts?  Anyone?

**Comment by artfuld** [comment]
So you would probably need to write a pretty big script for this. For that sort of complexity I would probably create a small program to do it instead.
Something like this.
1. Users, copy users one at a time. For each user keep track of the old Id and the new Id change the id's in every table that has a userid column.
You'd probably want to isolate the rows that you have changed aswell since there could be duplicate ids.

2. Same thing with the security, forum groups, forum, content, topics and every other thread :/.

This can certainly be done but the time it would take to sort this mess out and then create the actual program would probably not be worth your time unless you got 10 or more forums that you want to merge cross dnn.

**Comment by TBGoat** [comment]
The more I think about this the more complicated it gets.  I almost wonder if you couldn't integrate your current forums with their current database inside the larger website and just pass the user info back and forth to log in.  Even if you have to take the other server down, you could migrate to a seperate DB on the new server, delete all the modules but ActiveForums and work with that for these special forums. That might be the least painful option.

Otherwise, I think @artfuld has the only possible solution.  Its a lot harder than just moving to a fresh portal.
