### ISSUE TITLE
Show Topics of a Forum Directly without passing for the Forums List

### ISSUE THREAD

**Issue by ericktj** [ActiveForums/ActiveForums#263]
Hey, I will have a single forum in my site and it will be at the Home page, Is there a way I can show the Forum's Topics right away people gets to the site ?

I thought I could just redirect Home page to the URL where the Topics List shows up, but not sure if that's a convenient way

Thank you guys

**Comment by ericktj** [comment]
Hello, just want to know if is possible or not with the current module features so I don't spend too much time figuring it out - I've been checking the control panel options several times and look for the option but couldn't find something

I thought I just modify the Forums View template to be more like the topics view template but not sure if that's something I would need to do within the Module's code or there's a current feature I can use.

I also tried modifying the Forums View Template but changes I made to it are not showing up in the module

**Comment by artfuld** [comment]
Hey Ericktj,
I'm sorry but I just can't see this being done in AF without a bigger modification.

I can see if there's an ugly way to do this, but I can't guarantee that everything will work.

Just changing the template will not work as the data that is being fetched isn't the same.

**Comment by ericktj** [comment]
Thank you artfuld, any advise would be much apreciated

**Comment by artfuld** [comment]
Ok.. this will be a fix that you have to do locally. Let me know if you need any help.
It was way easier than I thought.

in Classic.ascx.cs line 119 insert this line.
if (ctl == DefaultView) ctl = "topicsview";

And in ForumBase.cs line 331 change to this
_forumId = 1

on my dev setup this seems to work with creating and replying. But you should probably do more testing.
This will set the Forum with ID 1 as the one to show, so that is the one you need to change permissions on.

**Comment by ericktj** [comment]
Hey artfuld, Thank you very much for taking the time of checking on this

Will do as you says and hopefully that will do it

**Comment by frozendnn** [comment]
You are talking about threaded view. I think when AF was still owned by AM, they were trying to do it. I saw a screenshot of a threaded view for AF. Nothing was released though.
