### ISSUE TITLE
I could use some real help regarding who viewed a post

### ISSUE THREAD

**Issue by supermansrf** [ActiveForums/ActiveForums#326]
I know I've asked about this before, but I'm asking anyone who can help me figure this out to please help. I have a potential legal issue and it involves a forum we have.  Specifically one post.  

I have the ability to see who is subscribed to a forum because I can go on the webmaster email and check the sent items.  So I know who has viewed a forum post notification. 

I can't however, figure out how the whole "read flag" system works.  The forum has to be tracking who viewed a post or a reply because it tracks views.  it also knows what you have any haven't read.  

If anyone can help me out, I would forever be grateful, and hopefully we could build this feature into the software as an admin tool.  But initially I need a quick and dirty way to see who viewed a post.  It could be a simple script to produce user ID's.  Ultimately I would like to see an admin button to see who has subscribed to a forum or a post and another button to see who has viewed a post.  I believe this is necessary for forum security.  

Can anyone please find a way for me to figure out who has seen a particular post?  I can ask my developer to look into this, but he would be learning from scratch.  I'm sure someone here knows this system.  

Thank you in advance.

**Comment by artfuld** [comment]
[sql.txt](https://github.com/ActiveForums/ActiveForums/files/3079/sql.txt)
Run this in ssms, you should get a list of who has read what topic and what was the last replyId when they read the topic and the date of last time. 

I agree that this would be a nice feature to implement to the forum itself, And since the data is stored already it should only be a question about collecting and showing the data for every page.
