### ISSUE TITLE
Search Results Page Crashes

### ISSUE THREAD

**Issue by passfire** [ActiveForums/ActiveForums#327]
I'm building a new site using  AF 6.2.8 on DNN 7.4.1, running on localhost currently.  I've ported forum data over from an older version of AF running on another site.

Whenever I do any search on any given combinations of parameters, there is an overly long wait followed by a DNN Error page and the exception event below is logged.   No matter how broad or restricted the search is, the wait time is always the same and the same error occurs.

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c671249b-cf59-4d88-a553-323396e62caa
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:e8srBLLelyIyogXtouXjBw==

Message:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

StackTrace:

InnerMessage:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

InnerStackTrace:

 at System.Web.UI.ControlCollection.RemoveAt(Int32 index) at System.Web.UI.ControlCollection.Clear() at DotNetNuke.Modules.ActiveForums.af_search. (EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by passfire** [comment]
I have determined that this issue is caused by incompatible data from a port I am doing from an older version of Active Forums.  The problem does not occur on a fresh install, so I am breaking it with incompatible data somehow.

**Comment by supermansrf** [comment]
I have had similar issues with ported data however mine was converted from DNN Forum and not an older version of AF.  I can tell you that what I found had to do with how AF was processing the html markup in the topic's subject line.  There are several characters that AF doesn't recognize from DNN forum.  I'm not sure if this will help but I'll attach a txt file that I've used to correct some of this.  

What you probably should do is start with the stuff that I've said "in the subject line" and see if that fixes your issue.  What I did was just go through posts after running this script and replace any other characters that I found weren't displaying properly.  Hope this helps. 

[sql script update html on posts and topics.txt](https://github.com/ActiveForums/ActiveForums/files/17953/sql.script.update.html.on.posts.and.topics.txt)

**Comment by supermansrf** [comment]
I should point out that there are multiple scripts on that file.  Each one does something slightly different and its possible that this wasn't all I had to do.  I do remember that one of the big things I had an issue with was the &39 and &amp so i would start with the first 2 scripts that are aimed at corrections to the subject line and not the body.

**Comment by passfire** [comment]
Thanks, I'll give it a try.  I was trying to find the exact post breaking the search by porting just one topic or reply at a time, but the trouble spot was thousands of posts in so I gave up trying to isolate it.  If the error message could include information like TopicId, ReplyId, ContentId etc. then it would be easier to locate where the problem data is located.

**Comment by supermansrf** [comment]
So I wanted to revisit this today as I have run across some more really old posts that were causing issues.  I wanted to clarify some of the things that I have found.

Somehow certain html characters got all messed up during my conversion.  For example today I ran across a post that showed &ndash; in the body of the topic.  I ran my script to try to convert &ndash; to - and it didn't work.  I located the topic ID, ran a sql script to find the content ID, then looked at the body in the database directly.  It reminded me of something.  

The change isn't just from &ndash; to - because what is actually showing up in the database is &amp;ndash;.  AF would have recognized everything fine if it was just &ndash; but somewhere along the line it decided to replace the leading & with &amp; making the whole thing a mess.  

So what I had to do to correct this was run the script to replace &amp;ndash; with - and that fixed this new one.  

I would suggest having a look through the dbo.Activeforums_Content table, looking at the body column and see if you can find anything in there that stands out.  You really shouldn't see any &xx; in there at all.  It should already be converted.  

Finding all of those entries and cleaning them up will most definitely fix your issue.  You just have to find them.  I'm sorry I didn't keep good notes on this as there were many characters that needed cleaned up.  I'm sure once you find these your answer will be fixed.   

Hope this helps. I may try to go back and restore an old backup, do the conversion again and try to write a script that will do all of these conversions in one sweep but that may be a while before I can do so.

**Comment by supermansrf** [comment]
Markdown removed a lot of my comment up above. I have tried to edit it.  Basically I have removed a bunch of & from before things.  I'm adding some extra . to my comment to hopefully get it to show up properly

**Comment by supermansrf** [comment]
And the period didn't work so I put a space between the & and ndash or & and amp

**Comment by passfire** [comment]
A better approach would be to fix the page that is rendering the search results so that it filters out any characters that cause problems instead of the user having to modify database entries.  This problem does not occur in version 4.3.5 of AF, so it was a more recent change that is causing the problem.

In version 4.3.5, I do have a problem where data created later than 2013 is not being included in the searches, which is an issue that doesn't happen in the latest version.   Any idea what could cause that?  I was hoping I could patch my 4.3.5 installation to fix that one problem and then I'd have no need to upgrade it.  I ran the queries to clean up the data that you sent me for the other problem, but it didn't fix this one.  I figure it must be a similar type of thing where data is breaking the search, since it worked fine up until sometime in 2013 and then just stopped returning results for anything later than that period.

**Comment by artfuld** [comment]
Hello,

If you can set up a development environment you could find the post that breaks the search within seconds. If you wan't help you could send me a copy of your site+db and I can debug it for you.
