### ISSUE TITLE
Inserted Image URLs not including port number on localhost

### ISSUE THREAD

**Issue by passfire** [ActiveForums/ActiveForums#328]
I'm developing a new site using AF 6.2.8 on DNN 7.4.1, running on localhost using webmatrix. I've ported forum data over from an older version of AF running on another site.

I believe this problem is specific to running on webmatrix/localhost.  When inserting images into a post, the images appear in the design view of the html editor but the auto-generated URL when viewed in the forum is failing to append the port number onto "localhost".  For example, when the URL required for the image is http://localhost:52075/Portals/0/activeforums_Attach/bike_roller_1.jpg, AF will leave off the port number and insert http://localhost/Portals/0/activeforums_Attach/bike_roller_1.jpg instead and the image will not display.  For the above example, the image tag used in the post references the image as src="/Portals/0/activeforums_Attach/bike_roller_1.jpg", which will correctly display the image in the Telerik editor's display mode.

**Comment by supermansrf** [comment]
@passfire I'm sorry for not responding sooner. I personally have no experience using localhost as everything I do is tested on live sites with URL's.  I'm guessing that AF doesn't recognize the : and port and that is most likely the problem which I'm sure you are aware.  Telerik is aware which is why your images will show in the editor display. 

I do however feel like I'm mainly repeating what you are saying and not really contributing anything here.  I'll leave this open and mark as a known issue so hopefully someone will address in the future.

**Comment by artfuld** [comment]
this is fixed with pull #334

**Comment by supermansrf** [comment]
I'll merge this into an updated 6.3 in a few hours

**Comment by artfuld** [comment]
passfire, please confirm if this is working for you when you got the time.

**Comment by passfire** [comment]
I just tested it and it works now.  Thanks!

**Comment by artfuld** [comment]
Thank you, I'll close this issue then.
