### ISSUE TITLE
Converting to AF from DNN Forums

### ISSUE THREAD

**Issue by joannschlosser** [ActiveForums/ActiveForums#385]
Is there a script or set of steps available to accomplish this?

**Comment by supermansrf** [comment]
Yes.  I believe that this is still over on the old codeplex page only.  Here is a link.  I have done this several times and it does work well.  Depending on the size of your forum, I would recommend running this from Management Studio if at all possible rather than Host > SQL but if you don't have a lot of content it isn't as big of a deal.  Just follow the directions regardless.  It's been a while since I have done this but I may remember some of it if asked lol.

Since this was written a while ago, I don't know if it would allow you to go from latest DNN Forum to the most recent AF.  You may want to try to convert to a version that was on codeplex first then upgrade AF after upgrading. 

I just wanted to get you an answer before I headed off to work.  If you need more help ask and I'll see what I can find in my notes.  

https://activeforums.codeplex.com/wikipage?title=Migrating%20from%20DNN%20Forums%205.0.3%20to%20Active%20Forums%205.0&referringTitle=Documentation

If that link doesn't work, use this and then look for the link to the migration page:

https://activeforums.codeplex.com/documentation

**Comment by supermansrf** [comment]
I just had a look at that page.  I believe that you can upgrade DNN Forums to the latest (if not done already) 5.0.3 or 5.0.4 I believe will work on DNN 7X.  Then convert to AF 5.2  Then you can upgrade from there to more recent version of AF

**Comment by joannschlosser** [comment]
Thanks!  Now, how about DNN8?  We just launched a brand new site and only now found the bug in DNN Forums.  It has been reported but no idea when it will be fixed.  I will refresh my local copy of the site and try it there.  That bug is the ONLY problem we have with the site but the forum is the most popular part of it, of course.


-------- Original Message --------
Subject: Re: [ActiveForums/ActiveForums] Converting to AF from DNN
Forums (#385)

**Comment by ChrisHammond** [comment]
That script/process from Codeplex should still work, might need a minor tweak or two, but should be a great place tos tart.

**Comment by joannschlosser** [comment]
Well, finally got to sit down with this.  I have installed AF5.02 and ran the script, cjh-CoreForumsToActiveForums-1.5.sql, but nothing happened.  The installed version of DNN Forums is 5.0.It completed without error, but I don't see any data in the AF tables and the AF install still shows the 3 out of the box forums and nothing else.I really want to upgrade this but I do not want to have to figure out another conversion on my own.What am I missing?  Thanks!JoAnn


-------- Original Message --------
Subject: Re: [ActiveForums/ActiveForums] Converting to AF from DNN
Forums (#385)

**Comment by joannschlosser** [comment]
Let me update this.  The ModuleID I used from the URL was incorrect.  I found the right one in the forum_groups table.  I reran it and it ran for a couple of minutes before it errorred out with a bunch of PK key errors against 'dbo.activeforums_Topics''dbo.activeforums_ForumTopics''dbo.dnntoaf_topics'I will try to look at it this weekend.  Too fried to fool with it right now.Thanks.JoAnnPS - should I be removing the out of the box demo data from AF?

**Comment by mitchelsellers** [comment]
@joannschlosser Yes, all demo data should be gone as well.  It could be trying to use id values that are not available.

**Comment by supermansrf** [comment]
Are you running the script from Host > SQL or Management Studio?

How much data (roughly) are you trying to convert?


Sent from my iPhone

On Feb 1, 2017, at 7:02 PM, Mitchel Sellers <notifications@github.com>
wrote:

@joannschlosser <https://github.com/joannschlosser> Yes, all demo data
should be gone as well. It could be trying to use id values that are not
available.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ActiveForums/ActiveForums/issues/385#issuecomment-276823857>,
or mute the thread

**Comment by joannschlosser** [comment]
Running it using the site not SSMS.  It is small and I wanted to time it.  When I got the right module ID for the DNN forum, it ran about 2 minutes and it looks right-ish - will have to do something the the forum creation dates, I assure you they were not created in 1899!  I did get some errors, but it looks like 3 for each troubled record, so I can look at those and see if there is something amiss with those records.  Could very well be because the DNN Forums data was converted from PHPBB and I had to figure that one out on my own and I probably missed something.I think I am doing okay for now.  The script has been a great blessing!That said, what version is being run on the ActiveForums website?  


-------- Original Message --------
Subject: Re: [ActiveForums/ActiveForums] Converting to AF from DNN
Forums (#385)

**Comment by ChrisHammond** [comment]
I'm running AF 6.3 on my DNN sites these days

**Comment by joannschlosser** [comment]
Thanks.  Looks like that is what the AF site is running.  Now a stupid question - but since this is my first full-featured DNN site - maybe not so stupidI have never upgraded a module.  How is this done?Thanks!JoAnn


-------- Original Message --------
Subject: Re: [ActiveForums/ActiveForums] Converting to AF from DNN
Forums (#385)

**Comment by supermansrf** [comment]
You basically just install the new version. New install and upgrade
are done the same way. As long as it's not the same version there is
no difference. If it is the same version it will warn you and prompt
to repair install.

**Comment by joannschlosser** [comment]
I just upgraded my local installation to 6.3 but it looks like it thinks it is 6.2.8?Anyway, I have the admin docs for 4.something here which are, of course, out of date.  Specifically, my questions are:Is there more current documentation available?Can I assign the general configuration and user role settings to all forums and groups once, then tweak the special ones or do I have to do each separately?  I am not above setting up one, then running a script to copy the settings to the rest.I don't see an option for saving attachments into the database in the current version.  Is this still an option?Thanks!JoAnn 


-------- Original Message --------
Subject: Re: [ActiveForums/ActiveForums] Converting to AF from DNN
Forums (#385)

**Comment by mitchelsellers** [comment]
Right now there is not any additional documentation that has been created, we would welcome additional contributors to assist in improving the documentation on the product.

In an effort to better manage issues with the Active Forums product I am going to close this item, as we do not have an item to "fix" as part of this at this time.  (Email if you have any questions.)
