### ISSUE TITLE
"Like" and "Thank" for the post

### ISSUE THREAD

**Issue by hismightiness** [ActiveForums/ActiveForums#436]
It would be super-useful for today's style of communication to have a one-click way to like a specific post and reply to the post.  When you do, something visual should indicate that the "like" occurred, as well as display the number of likes.  Clicking on the number of likes should show the people that liked the post.

The same criteria would apply for "thank."  "Thank the user for this post/reply."  (I'm not married to this one, as a "Like" feature could seem redundant.  

In both scenarios, the data storage needs to be clearly queryable so that we can give community points in places like the dnncommunity.org website.  :)

**Comment by wmorgenweck** [comment]
There was a “like” option at some point. I believe it was integrated with the journal. I’ll see if I can find it in an old code base. 

Thanks,
Will

**Comment by supermansrf** [comment]
There is a like button on our forum. It was an added feature at some point.
Just a thumb icon to click on. Simple.



Sent from my iPhone

On Jun 12, 2019, at 3:07 PM, Will Morgenweck <notifications@github.com>
wrote:

There was a “like” option at some point. I believe it was integrated with
the journal. I’ll see if I can find it in an old code base.

Thanks,
Will

> On Jun 12, 2019, at 12:48 PM, Will Strohl <notifications@github.com>
wrote:
>
> It would be super-useful for today's style of communication to have a
one-click way to like a specific post and reply to the post. When you do,
something visual should indicate that the "like" occurred, as well as
display the number of likes. Clicking on the number of likes should show
the people that liked the post.
>
> The same criteria would apply for "thank." "Thank the user for this
post/reply." (I'm not married to this one, as a "Like" feature could seem
redundant.
>
> In both scenarios, the data storage needs to be clearly queryable so that
we can give community points in places like the dnncommunity.org website. :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ActiveForums/ActiveForums/issues/436?email_source=notifications&email_token=ABONEMPCTRBYUXI7ZTBQMELP2FCP5A5CNFSM4HXLFIG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXRPXXI#issuecomment-501414877>,
or mute the thread

**Comment by hismightiness** [comment]
Never mind, @wmorgenweck ... This feature already exists.  I missed it initially, but that's my fault.
