### ISSUE TITLE
Breadcrumbs do not show parent group when opening a child group

### ISSUE THREAD

**Issue by sjthompsonengl** [ActiveForums/ActiveForums#56]
I use groups for forums e.g.

Support --> Product --> Product area

The breadcrumb links do not show the group level, so return you to the wrong place
![forumlist](https://f.cloud.github.com/assets/6450312/2126125/8a5af00a-925d-11e3-9626-426c71064979.jpg)
![breadcrumb](https://f.cloud.github.com/assets/6450312/2126126/8a6e1da6-925d-11e3-8f3d-74204101f770.jpg)

The attachments show the forum list and then the breadcrumb when I select the "Installation" forum
##

**Comment by artfuld** [comment]
I have been looking at this and it shouldn't be to hard. The problem I'm having is the the breadcrumb divider.
My fix for this was to insert a new token [BREADCRUMBDIVIDER] [/BREADCRUMBDIVIDER] and in between you can set whatever you want to be shown between the breadcrumbs.
The reason for this is that is you set in the template [GROUPLINK] > [PARENTFORUMLINK] > [MAINFORUMLINK] it will show like this if you're not in a child group
Group > > main
since it removes the parentforum cause there is none.

Is this excusable or does anyone have another idea for how to do it?
